- members.yaml
> docs : wonjunYou 멤버 추가

- members.yaml
> docs : devholic22 멤버 추가

- members.yaml
> docs: tlarbals824 멤버 추가

- members.yaml
> docs: Gopistol 멤버 추가

- members.yaml
> docs: update conference study members

- members.yaml
- teams.yaml
> Update teams.yaml, members.yaml

- members.yaml
- teams.yaml
> 알고리즘 스터디 멤버 신청 PR 올립니다.

- members.yaml
- teams.yaml
> add: 23-13 멤버 신청합니다

- members.yaml
- teams.yaml
> Github ORG 멤버 신청 및 스터디 가입 PR

- members.yaml
- teams.yaml
> update: 멤버 및 스터디 추가 부탁드립니다.

- members.yaml
- teams.yaml
member.yaml 파일과 teams.yaml 파일에 각각 제 github username 추가 했습니다!
디자인 패턴 스터디 잘 참여 하겠습니다! :)
> Github ORG 멤버 신청 및 스터디 Team 추가 

- members.yaml
- teams.yaml
23-11(데이터 중심 애플리케이션 설계) 스터디 팀 참여합니다.
> 23-11(데이터 중심 애플리케이션 설계) 스터디 팀 참여합니다.

- members.yaml
- teams.yaml
> update : member-add-jijihoon96

- teams.yaml
> Docs : 디자인패턴 팀에 이름 추가

- members.yaml
- teams.yaml
> 23-10-DesignPattern 멤버 추가

- members.yaml
- teams.yaml
데이터중심어플리케이션설계 스터디 참여 신청드립니다.
감사합니다.
> docs: add member (menthamin)

- teams.yaml
- 기존 멤버 목록에 포함된 상태로 `members.yaml` 파일은 미수정
- `teams.yaml` 파일에 계정명 추가
> 디자인패턴 스터디 참여

- members.yaml
- teams.yaml
디자인 패턴 스터디 참가를 위해 pr을 보냅니다.
확인 부탁드립니다.
> 스터디 참가를 위한 pr 

- members.yaml
- teams.yaml
> teams, members에 이름 추가 했습니다.

- members.yaml
- teams.yaml
23년 4분기 도커교과서 스터디1에 참여하는 오원종입니다.
> docs: add member, team

- members.yaml
> 신규 스터디원 docs: add member 추가 PR

- members.yaml
> docs : 신규 멤버 추가 PR 입니다 (0r0loo)

- members.yaml
> 신규 멤버 추가 PR 입니다 (startdata)

- members.yaml
안녕하세요. 이본행입니다.
멤버 추가 요청드립니다. 초대 감사합니다.
> 멤버 추가 - 이본행

- members.yaml
> feat: add qkrdmstlr3

- members.yaml
- teams.yaml
안녕하세요. 박소영입니다.
멤버 추가 요청드려요!
감사합니다!
> 멤버 추가 - 박소영

- members.yaml
> 멤버추가 - 임하늘

- teams.yaml
> 팀 이름 추가 - 박소영

- members.yaml
- teams.yaml
> 신규 멤버 추가 PR 입니다 - 서제민

- members.yaml
> 팀 이름 추가 - 이준호 (#87)

- members.yaml
- teams.yaml
> mollder add team, member

- members.yaml
- teams.yaml
teams.yaml
members.yaml
모두 이용혁 yonghyeokrhee 추가
> 스터디원 추가 PR

- teams.yaml
> 멤버 추가 - 김동미

- teams.yaml
> 멤버 추가 - 김해지

- members.yaml
- teams.yaml
민기님 멤버에 추가
민기님, 하늘님, 예성님 팀에 추가
> update teams ans members

- members.yaml
- teams.yaml
안녕하세요! 이번에 친절한 SQL 튜닝 스터디에 참여하게된 이세희입니다! 해당 레포지토리 안내사항보고 PR 올립니다! 🙇‍♀️
`member.yaml`에는 이름을 추가했는데 `teams.yaml`에는  참여하는 스터디(`친절한 SQL 튜닝`) 섹션이 안보이는 것 같습니다! 나중에 항목이 추가될 때 제 이름을 추가하면 되는 것인지 여쭤봅니다! 
앞으로 잘 부탁드립니다! :)
> 신규 멤버 신청합니다!

- members.yaml
- teams.yaml
- 신규 멤버 및 SQL 튜닝 스터디 함께 신청합니다!!
> 신규 멤버 및 스터디 신청합니다!

- members.yaml
- teams.yaml
2024년 1Q Study - 친절한 SQL 튜닝 스터디 멤버입니다.
감사합니다.
> 신규 멤버 추가 - SimDaeSoo
